In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
s = pd.Series([1,3,5,np.nan,6,8])

In [3]:
s

0     1
1     3
2     5
3   NaN
4     6
5     8
dtype: float64

In [4]:
dates = pd.date_range('20130101',periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D', tz=None)

In [5]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))

In [6]:
df

A         B         C         D
2013-01-01 -1.369175  1.701948 -1.381653  0.137112
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270
2013-01-03  0.327760  0.409381 -1.208742 -0.014488
2013-01-04 -0.545706  0.227194 -0.055860  0.082593
2013-01-05  1.291915  0.610380  0.234046  0.177582
2013-01-06 -0.639157  2.217350 -1.281044 -0.522820

In [10]:
df2 = pd.DataFrame({'A':1.,
                   'B':pd.Timestamp('20130102'),
                   'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                   'D':np.array([3]*4,dtype='int32'),
                   'E':pd.Categorical(['test','train','test','train']),
                   'F':'foo'})
df2

A          B  C  D      E    F
0  1 2013-01-02  1  3   test  foo
1  1 2013-01-02  1  3  train  foo
2  1 2013-01-02  1  3   test  foo
3  1 2013-01-02  1  3  train  foo

In [11]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [12]:
df.head()

A         B         C         D
2013-01-01 -1.369175  1.701948 -1.381653  0.137112
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270
2013-01-03  0.327760  0.409381 -1.208742 -0.014488
2013-01-04 -0.545706  0.227194 -0.055860  0.082593
2013-01-05  1.291915  0.610380  0.234046  0.177582

In [13]:
df.tail(3)

A         B         C         D
2013-01-04 -0.545706  0.227194 -0.055860  0.082593
2013-01-05  1.291915  0.610380  0.234046  0.177582
2013-01-06 -0.639157  2.217350 -1.281044 -0.522820

In [19]:
print df.index
print df.columns
print df.values

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D', tz=None)
Index([u'A', u'B', u'C', u'D'], dtype='object')
[[-1.3691751   1.70194756 -1.38165304  0.1371118 ]
 [-2.00051476 -0.59744258  0.65569052 -2.18327031]
 [ 0.32776042  0.4093808  -1.208742   -0.01448835]
 [-0.54570553  0.22719366 -0.05586036  0.08259319]
 [ 1.29191497  0.61037954  0.2340458   0.17758168]
 [-0.63915685  2.2173505  -1.28104415 -0.52281987]]


In [20]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.489146  0.761468 -0.506261 -0.387215
std    1.176767  1.027908  0.890070  0.916271
min   -2.000515 -0.597443 -1.381653 -2.183270
25%   -1.186671  0.272740 -1.262969 -0.395737
50%   -0.592431  0.509880 -0.632301  0.034052
75%    0.109394  1.429056  0.161569  0.123482
max    1.291915  2.217350  0.655691  0.177582

In [21]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.369175   -2.000515    0.327760   -0.545706    1.291915   -0.639157
B    1.701948   -0.597443    0.409381    0.227194    0.610380    2.217350
C   -1.381653    0.655691   -1.208742   -0.055860    0.234046   -1.281044
D    0.137112   -2.183270   -0.014488    0.082593    0.177582   -0.522820

In [25]:
df.sort_index(axis=1,ascending=False)

D         C         B         A
2013-01-01  0.137112 -1.381653  1.701948 -1.369175
2013-01-02 -2.183270  0.655691 -0.597443 -2.000515
2013-01-03 -0.014488 -1.208742  0.409381  0.327760
2013-01-04  0.082593 -0.055860  0.227194 -0.545706
2013-01-05  0.177582  0.234046  0.610380  1.291915
2013-01-06 -0.522820 -1.281044  2.217350 -0.639157

In [28]:
df.sort('B')
#not df.sort_values(by='B')

A         B         C         D
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270
2013-01-04 -0.545706  0.227194 -0.055860  0.082593
2013-01-03  0.327760  0.409381 -1.208742 -0.014488
2013-01-05  1.291915  0.610380  0.234046  0.177582
2013-01-01 -1.369175  1.701948 -1.381653  0.137112
2013-01-06 -0.639157  2.217350 -1.281044 -0.522820

In [29]:
df['A']

2013-01-01   -1.369175
2013-01-02   -2.000515
2013-01-03    0.327760
2013-01-04   -0.545706
2013-01-05    1.291915
2013-01-06   -0.639157
Freq: D, Name: A, dtype: float64

In [30]:
df[0:3]

A         B         C         D
2013-01-01 -1.369175  1.701948 -1.381653  0.137112
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270
2013-01-03  0.327760  0.409381 -1.208742 -0.014488

In [35]:
df['20130102':'20130104']

A         B         C         D
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270
2013-01-03  0.327760  0.409381 -1.208742 -0.014488
2013-01-04 -0.545706  0.227194 -0.055860  0.082593

In [39]:
print df.loc[dates[0]]
print dates[0]

A   -1.369175
B    1.701948
C   -1.381653
D    0.137112
Name: 2013-01-01 00:00:00, dtype: float64
2013-01-01 00:00:00


In [40]:
df.loc[:,['A','B']]

A         B
2013-01-01 -1.369175  1.701948
2013-01-02 -2.000515 -0.597443
2013-01-03  0.327760  0.409381
2013-01-04 -0.545706  0.227194
2013-01-05  1.291915  0.610380
2013-01-06 -0.639157  2.217350

In [41]:
df.loc['20130102':'20130104',['A','B']]

A         B
2013-01-02 -2.000515 -0.597443
2013-01-03  0.327760  0.409381
2013-01-04 -0.545706  0.227194

In [42]:
df.loc['20130102',['A','B']]

A   -2.000515
B   -0.597443
Name: 2013-01-02 00:00:00, dtype: float64

In [43]:
df.loc[dates[0],'A']

-1.3691751011136437

In [44]:
df.at[dates[0],'A']

-1.3691751011136437

In [45]:
df.iloc[3]

A   -0.545706
B    0.227194
C   -0.055860
D    0.082593
Name: 2013-01-04 00:00:00, dtype: float64

In [46]:
df.iloc[3:5,0:2]

A         B
2013-01-04 -0.545706  0.227194
2013-01-05  1.291915  0.610380

In [47]:
df.iloc[[1,2,4],0:2]

A         B
2013-01-02 -2.000515 -0.597443
2013-01-03  0.327760  0.409381
2013-01-05  1.291915  0.610380

In [48]:
df.iloc[1:3,:]

A         B         C         D
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270
2013-01-03  0.327760  0.409381 -1.208742 -0.014488

In [49]:
df.iloc[:,1:3]

B         C
2013-01-01  1.701948 -1.381653
2013-01-02 -0.597443  0.655691
2013-01-03  0.409381 -1.208742
2013-01-04  0.227194 -0.055860
2013-01-05  0.610380  0.234046
2013-01-06  2.217350 -1.281044

In [50]:
df.iloc[1,1]

-0.59744257738016626

In [51]:
df.iat[1,1]

-0.59744257738016626

In [52]:
df[df.A > 0]

A         B         C         D
2013-01-03  0.327760  0.409381 -1.208742 -0.014488
2013-01-05  1.291915  0.610380  0.234046  0.177582

In [54]:
print df[df>0]
print df>0

                   A         B         C         D
2013-01-01       NaN  1.701948       NaN  0.137112
2013-01-02       NaN       NaN  0.655691       NaN
2013-01-03  0.327760  0.409381       NaN       NaN
2013-01-04       NaN  0.227194       NaN  0.082593
2013-01-05  1.291915  0.610380  0.234046  0.177582
2013-01-06       NaN  2.217350       NaN       NaN
                A      B      C      D
2013-01-01  False   True  False   True
2013-01-02  False  False   True  False
2013-01-03   True   True  False  False
2013-01-04  False   True  False   True
2013-01-05   True   True   True   True
2013-01-06  False   True  False  False


In [56]:
df2 = df.copy()
df2['E'] = ['one','one','two','three','four','three']
df2

A         B         C         D      E
2013-01-01 -1.369175  1.701948 -1.381653  0.137112    one
2013-01-02 -2.000515 -0.597443  0.655691 -2.183270    one
2013-01-03  0.327760  0.409381 -1.208742 -0.014488    two
2013-01-04 -0.545706  0.227194 -0.055860  0.082593  three
2013-01-05  1.291915  0.610380  0.234046  0.177582   four
2013-01-06 -0.639157  2.217350 -1.281044 -0.522820  three

In [57]:
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03  0.327760  0.409381 -1.208742 -0.014488   two
2013-01-05  1.291915  0.610380  0.234046  0.177582  four

In [58]:
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20130102',periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [59]:
df['F']=s1

In [60]:
df.at[dates[0],'A'] = 0

In [61]:
df.iat[0,1] = 0

In [62]:
df.loc[:,'D'] = np.array([5]*len(df))

In [63]:
df

A         B         C  D   F
2013-01-01  0.000000  0.000000 -1.381653  5 NaN
2013-01-02 -2.000515 -0.597443  0.655691  5   1
2013-01-03  0.327760  0.409381 -1.208742  5   2
2013-01-04 -0.545706  0.227194 -0.055860  5   3
2013-01-05  1.291915  0.610380  0.234046  5   4
2013-01-06 -0.639157  2.217350 -1.281044  5   5

In [64]:
df2 = df.copy()
df2[df2 > 0] = -df2
df2

A         B         C  D   F
2013-01-01  0.000000  0.000000 -1.381653 -5 NaN
2013-01-02 -2.000515 -0.597443 -0.655691 -5  -1
2013-01-03 -0.327760 -0.409381 -1.208742 -5  -2
2013-01-04 -0.545706 -0.227194 -0.055860 -5  -3
2013-01-05 -1.291915 -0.610380 -0.234046 -5  -4
2013-01-06 -0.639157 -2.217350 -1.281044 -5  -5

In [65]:
df1 = df.reindex(index=dates[0:4],columns=list(df.columns)+['E'])
df1.loc[dates[0]:dates[1],'E'] = 1
df1

A         B         C  D   F   E
2013-01-01  0.000000  0.000000 -1.381653  5 NaN   1
2013-01-02 -2.000515 -0.597443  0.655691  5   1   1
2013-01-03  0.327760  0.409381 -1.208742  5   2 NaN
2013-01-04 -0.545706  0.227194 -0.055860  5   3 NaN

In [69]:
df1.dropna(how='any')

A         B         C  D  F  E
2013-01-02 -2.000515 -0.597443  0.655691  5  1  1

In [70]:
df1.fillna(value=5)

A         B         C  D  F  E
2013-01-01  0.000000  0.000000 -1.381653  5  5  1
2013-01-02 -2.000515 -0.597443  0.655691  5  1  1
2013-01-03  0.327760  0.409381 -1.208742  5  2  5
2013-01-04 -0.545706  0.227194 -0.055860  5  3  5

In [71]:
pd.isnull(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [72]:
df.mean()

A   -0.260950
B    0.477810
C   -0.506261
D    5.000000
F    3.000000
dtype: float64

In [73]:
df.mean(1)

2013-01-01    0.904587
2013-01-02    0.811547
2013-01-03    1.305680
2013-01-04    1.525126
2013-01-05    2.227268
2013-01-06    2.059430
Freq: D, dtype: float64

In [74]:
s=pd.Series([1,3,5,np.nan,6,8],index=dates).shift(2)
s

2013-01-01   NaN
2013-01-02   NaN
2013-01-03     1
2013-01-04     3
2013-01-05     5
2013-01-06   NaN
Freq: D, dtype: float64

In [75]:
df.sub(s,axis='index')

A         B         C   D   F
2013-01-01       NaN       NaN       NaN NaN NaN
2013-01-02       NaN       NaN       NaN NaN NaN
2013-01-03 -0.672240 -0.590619 -2.208742   4   1
2013-01-04 -3.545706 -2.772806 -3.055860   2   0
2013-01-05 -3.708085 -4.389620 -4.765954   0  -1
2013-01-06       NaN       NaN       NaN NaN NaN

In [76]:
df.apply(np.cumsum)

A         B         C   D   F
2013-01-01  0.000000  0.000000 -1.381653   5 NaN
2013-01-02 -2.000515 -0.597443 -0.725963  10   1
2013-01-03 -1.672754 -0.188062 -1.934705  15   3
2013-01-04 -2.218460  0.039132 -1.990565  20   6
2013-01-05 -0.926545  0.649511 -1.756519  25  10
2013-01-06 -1.565702  2.866862 -3.037563  30  15

In [77]:
df.apply(lambda x: x.max() - x.min())

A    3.292430
B    2.814793
C    2.037344
D    0.000000
F    4.000000
dtype: float64

In [78]:
s = pd.Series(np.random.randint(0,7,size=10))
s

0    4
1    4
2    5
3    3
4    5
5    5
6    6
7    4
8    2
9    2
dtype: int64

In [79]:
s.value_counts()

5    3
4    3
2    2
6    1
3    1
dtype: int64